DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE AUTHORS(ID INT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRES(ID INT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOKS(ID INT PRIMARY KEY, TITLE VARCHAR(255), AUTHOR_ID INT, GENRE_ID INT,
                  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS,
                  FOREIGN KEY (GENRE_ID) REFERENCES GENRES);