DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE AUTHORS(ID INTEGER NOT NULL AUTO_INCREMENT, NAME VARCHAR(255),
                     PRIMARY KEY (id));
CREATE TABLE GENRES(ID INTEGER NOT NULL AUTO_INCREMENT, NAME VARCHAR(255),
                    PRIMARY KEY (id));
CREATE TABLE BOOKS(ID INTEGER NOT NULL AUTO_INCREMENT, TITLE VARCHAR(255), AUTHOR_ID INT, GENRE_ID INT,
                   FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS,
                   FOREIGN KEY (GENRE_ID) REFERENCES GENRES,
                   PRIMARY KEY (id));
CREATE TABLE COMMENTS(ID INTEGER NOT NULL AUTO_INCREMENT, BOOK_ID INT, TEXT VARCHAR(2000),
                      FOREIGN KEY (BOOK_ID) REFERENCES BOOKS,
                      PRIMARY KEY (id));

